version: '3.9'

services:
  nginx:
    container_name: k3i-nginx
    image: nginx:1.23.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/cert:/etc/nginx/ssl
      - /var/www/k3i:/var/www/k3i
    depends_on:
      - php81
      - php73
      - node18
      - pgadmin
    networks:
      - app-network
  
  php81:
    container_name: k3i-php81
    build: ./config/php81
    volumes:
      - /var/www/k3i:/var/www/k3i
    networks:
      - app-network
  
  php73:
    container_name: k3i-php73
    build: ./config/php73
    volumes:
      - /var/www/k3i:/var/www/k3i
    networks:
      - app-network
  
  node18:
    container_name: k3i-node18
    build: ./config/node18
    volumes:
      - /var/www/k3i:/var/www/k3i
    networks:
      - app-network
  
  mysql:
    container_name: k3i-mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    container_name: k3i-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/dump:/var/lib/postgresql/dump
    networks:
      - app-network
  
  pgadmin:
    container_name: k3i-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge